import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { loadGbmModel, predictGbm } from "../src/gbm/index.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const MODEL_PATH = resolve(__dirname, "../../../.tmp/models/gbm_residual.json");

// Reference probabilities generated by the real Python runtime:
//   xgb.XGBClassifier(); booster.load_model(MODEL_PATH); model.predict_proba(x)
// against the same saved model this TS shim loads — ground truth for the
// tree-walking re-implementation, not a value chosen to make the test pass.
describe("predictGbm (TS XGBoost tree-walker) vs Python xgboost ground truth", () => {
  const model = loadGbmModel(MODEL_PATH);

  it("matches Python on an all-zeros feature row", () => {
    const x = new Array(95).fill(0);
    const probs = predictGbm(model, x);
    const expected = [0.6438524723052979, 0.15855282545089722, 0.19759471714496613];
    expect(probs[0]).toBeCloseTo(expected[0]!, 4);
    expect(probs[1]).toBeCloseTo(expected[1]!, 4);
    expect(probs[2]).toBeCloseTo(expected[2]!, 4);
  });

  it("matches Python on an odds+elo-populated row", () => {
    const x = new Array(95).fill(0);
    x[0] = 0.45; // mktH
    x[1] = 0.27; // mktD
    x[2] = 0.28; // mktA
    x[75] = 1550; // eloHome
    x[76] = 1480; // eloAway
    x[77] = 70; // eloDiff
    const probs = predictGbm(model, x);
    const expected = [0.6069156527519226, 0.18873852491378784, 0.20434582233428955];
    expect(probs[0]).toBeCloseTo(expected[0]!, 4);
    expect(probs[1]).toBeCloseTo(expected[1]!, 4);
    expect(probs[2]).toBeCloseTo(expected[2]!, 4);
  });

  it("matches Python on a seeded-random row (np.random.default_rng(42))", () => {
    const x = [
      0.30471707975443135, -1.0399841062404955, 0.7504511958064572, 0.9405647163912139,
      -1.9510351886538364, -1.302179506862318, 0.12784040316728537, -0.3162425923435822,
      -0.016801157504288795, -0.85304392757358, 0.8793979748628286, 0.7777919354289483,
      0.06603069756121605, 1.1272412069680329, 0.4675093422520456, -0.8592924628832382,
      0.36875078408249884, -0.9588826008289989, 0.8784503013072725, -0.049925910986252896,
      -0.18486236354526056, -0.6809295444039414, 1.2225413386740303, -0.15452948206880215,
      -0.4283278221631072, -0.3521335504882296, 0.5323091855533487, 0.36544406436407834,
      0.4127326115959884, 0.43082100300788273, 2.1416476008704612, -0.4064150163846156,
      -0.5122427290715373, -0.8137727282478777, 0.6159794225754956, 1.1289722927208916,
      -0.11394745765487507, -0.840156476962528, -0.8244812156912396, 0.6505927878247011,
      0.7432541712034423, 0.543154268305195, -0.6655097072886943, 0.23216132306671977,
      0.11668580914072822, 0.21868859672901295, 0.8714287779481898, 0.22359554877468227,
      0.6789135630718949, 0.06757906948889146, 0.28911939868998415, 0.6312882258385404,
      -1.4571558198556664, -0.31967121635730134, -0.4703726542927955, -0.6388778482433419,
      -0.27514225122668373, 1.4949413112343959, -0.8658311156932432, 0.9682783545914808,
      -1.6828697716158048, -0.33488502998577485, 0.1627530651050056, 0.5862223313592781,
      0.711226579792855, 0.7933472351999252, -0.3487250722484376, -0.46235179266456716,
      0.8579758812571538, -0.1913043248816149, -1.2756863233379219, -1.1332872140034806,
      -0.9194522860016113, 0.49716074405376404, 0.14242573607056525, 0.6904853540677682,
      -0.42725264633653426, 0.15853969107671423, 0.6255903939673367, -0.3093465397202384,
      0.45677523755741145, -0.6619259410666513, -0.3630538465650718, -0.3817378939983291,
      -1.1958396455890397, 0.4869724807855818, -0.46940234020272387, 0.01249411872768743,
      0.48074665890590895, 0.4465311760299441, 0.6653851089727862, -0.09848548450942361,
      -0.42329831204415375, -0.07971821090639905, -1.6873344339580298,
    ];
    const probs = predictGbm(model, x);
    const expected = [0.46741434931755066, 0.21935124695301056, 0.3132343888282776];
    expect(probs[0]).toBeCloseTo(expected[0]!, 4);
    expect(probs[1]).toBeCloseTo(expected[1]!, 4);
    expect(probs[2]).toBeCloseTo(expected[2]!, 4);
  });
});
